"""Add login_attempt table for login throttling

Revision ID: 11abb330238d
Revises: 4048f830933b
Create Date: 2026-09-09 15:20:00.891320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11abb330238d'
down_revision = '4048f830933b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schluessel', sa.String(length=255), nullable=False),
    sa.Column('zeitstempel', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_attempt_schluessel'), ['schluessel'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempt_zeitstempel'), ['zeitstempel'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_attempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_attempt_zeitstempel'))
        batch_op.drop_index(batch_op.f('ix_login_attempt_schluessel'))

    op.drop_table('login_attempt')
    # ### end Alembic commands ###
