"""Index ticket columns used for filtering

Revision ID: 25ff72ef792a
Revises: 11abb330238d
Create Date: 2026-09-09 17:22:22.446596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ff72ef792a'
down_revision = '11abb330238d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_ersteller_id'), ['ersteller_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_zugewiesen_an_id'), ['zugewiesen_an_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_zugewiesen_an_id'))
        batch_op.drop_index(batch_op.f('ix_ticket_team_id'))
        batch_op.drop_index(batch_op.f('ix_ticket_status'))
        batch_op.drop_index(batch_op.f('ix_ticket_ersteller_id'))

    # ### end Alembic commands ###
