"""Add prioritaet_geaendert to historien_aktion

Revision ID: 4048f830933b
Revises: b26d611886d8
Create Date: 2026-09-09 12:27:20.731396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4048f830933b'
down_revision = 'b26d611886d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_history', schema=None) as batch_op:
        batch_op.alter_column('aktion',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('STATUS_GEAENDERT', 'ZUGEWIESEN', 'TEAM_GEWECHSELT', 'PRIORITAET_GEAENDERT', name='historienaktion'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_history', schema=None) as batch_op:
        batch_op.alter_column('aktion',
               existing_type=sa.Enum('STATUS_GEAENDERT', 'ZUGEWIESEN', 'TEAM_GEWECHSELT', 'PRIORITAET_GEAENDERT', name='historienaktion'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)

    # ### end Alembic commands ###
