"""Initial schema

Revision ID: 7b05cfae232c
Revises: 
Create Date: 2026-09-09 03:19:27.555684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b05cfae232c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_gruppe_user', sa.String(length=255), nullable=True),
    sa.Column('ldap_server', sa.String(length=255), nullable=True),
    sa.Column('ldap_port', sa.Integer(), nullable=True),
    sa.Column('ldap_use_ssl', sa.Boolean(), nullable=False),
    sa.Column('ldap_base_dn', sa.String(length=255), nullable=True),
    sa.Column('ldap_bind_dn', sa.String(length=255), nullable=True),
    sa.Column('smtp_host', sa.String(length=255), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_from', sa.String(length=255), nullable=True),
    sa.Column('anhang_max_groesse_mb', sa.Integer(), nullable=False),
    sa.Column('alte_tickets_tage', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ad_gruppe_agenten', sa.String(length=255), nullable=True),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_username', sa.String(length=255), nullable=True),
    sa.Column('anzeigename', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('ist_admin', sa.Boolean(), nullable=False),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('passwort_hash', sa.String(length=255), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.Column('letzter_login_am', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ad_username')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'name', name='uq_category_team_name')
    )
    op.create_table('team_memberships',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'team_id')
    )
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titel', sa.String(length=255), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('ersteller_id', sa.Integer(), nullable=False),
    sa.Column('zugewiesen_an_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('OFFEN', 'IN_BEARBEITUNG', 'GELOEST', 'GESCHLOSSEN', name='ticketstatus'), nullable=False),
    sa.Column('prioritaet', sa.Enum('NIEDRIG', 'MITTEL', 'HOCH', name='ticketprioritaet'), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.Column('aktualisiert_am', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['ersteller_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['zugewiesen_an_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('sichtbarkeit', sa.Enum('OEFFENTLICH', 'INTERN', name='sichtbarkeit'), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('aktion', sa.Enum('STATUS_GEAENDERT', 'ZUGEWIESEN', 'TEAM_GEWECHSELT', name='historienaktion'), nullable=False),
    sa.Column('alter_wert', sa.String(length=255), nullable=True),
    sa.Column('neuer_wert', sa.String(length=255), nullable=True),
    sa.Column('ausgefuehrt_von_id', sa.Integer(), nullable=False),
    sa.Column('zeitstempel', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ausgefuehrt_von_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('dateiname', sa.String(length=255), nullable=False),
    sa.Column('pfad', sa.String(length=1024), nullable=False),
    sa.Column('groesse_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('hochgeladen_von_id', sa.Integer(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(ticket_id IS NOT NULL AND comment_id IS NULL) OR (ticket_id IS NULL AND comment_id IS NOT NULL)', name='ck_attachment_exactly_one_parent'),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['hochgeladen_von_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachment')
    op.drop_table('ticket_history')
    op.drop_table('comment')
    op.drop_table('ticket')
    op.drop_table('team_memberships')
    op.drop_table('category')
    op.drop_table('user')
    op.drop_table('team')
    op.drop_table('settings')
    # ### end Alembic commands ###
