"""Add smtp_username to settings

Revision ID: b26d611886d8
Revises: 7b05cfae232c
Create Date: 2026-09-09 03:34:42.333660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b26d611886d8'
down_revision = '7b05cfae232c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('smtp_username', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('smtp_username')

    # ### end Alembic commands ###
